[package]
name = "rsstv"
version = "0.1.0"
edition = "2024"

[dependencies]
biquad = "0.5.0"
clap = { version = "4.5.31", features = ["derive"] }
cpal = "0.15.3"
hilbert_transform = "0.1.1"
image = "0.25.5"
num-complex = "0.4.6"
simple-plot = "0.1.2"
wavers = "1.5.1"
